language: python
os: linux

python:
  - "3.8"

install:
  - pip install sphinx
  - pip install --force-reinstall "urllib3==1.26.16"
  - pip list
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"

script:
  - make html

deploy:
  provider: pages
  repo: ludwig-cf/ludwig-cf.github.io
  target_branch: master
  local_dir: _build/html
  github_token: $STATIC_WEBSITE_TOKEN
  skip_cleanup: true
  on:
    branch: develop
